---
galaxy_info:
  role_name: metricbeat
  author: Ted Cook
  description: An Ansible role to install and configure metricbeat
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - metricbeat

dependencies:
  - name: nephelaiio.plugins
    version: 1.0.23
  - name: nephelaiio.elastic_repo
    version: 2.0.0
    when: false
