# vim: ts=2 sw=2 et :
---
language: python

python:
  - 2.7
  - 3.7
  - 3.8

sudo: required

install:
  - pip install -r requirements.txt

script:
  - make

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
