---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint tasks/*
  flake8
platforms:
  - name: centos7
    image: centos:7
    privileged: yes
    command: /usr/sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: xenial
    image: ubuntu:xenial
    privileged: yes
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: bionic
    image: ubuntu:bionic
    privileged: yes
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: stretch
    image: debian:stretch
    privileged: yes
    command: /sbin/init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  inventory:
    vars:
      metricbeat_package_hold: yes
scenario:
  name: default
verifier:
  name: testinfra
