---
- hosts: apache
  user: ubuntu
  roles:
  - apache
  - geerlingguy.filebeat
  - nephelaiio.metricbeat

- hosts: wordpress
  user: ubuntu
  vars_files:
    ['roles/wordpress/vars/vault','roles/wordpress/vars/loadbalancer.yml']
  roles:
  - php
  - wordpress
